### ISSUE TITLE
get table width

### ISSUE THREAD

**Issue by fretn** [RyanBluth/term-table-rs#5]
First of all thanks for your nice library it's really useful for me.

Is there a way to get the width of the table before it is printed ?

**Comment by RyanBluth** [comment]
There is a `calculate_max_column_widths` function on Table but it isn't a public currently. It returns the max width for each column, so it should be possible to use that along with the width of the characters in the table style to compute the width of the table. If you want to take a stab at adding that in then that'd be great. If not I can probably take a look at it in the next week or so

**Comment by fretn** [comment]
the hacky solution should be okay, I didn't think that far, thanks :)

`table.render().find("\n")` gives the width of the table
