### ISSUE TITLE
Comparison with other 'table' libraries

### ISSUE THREAD

**Issue by danieleades** [RyanBluth/term-table-rs#9]
There are now a few libraries for pretty-printing tables to the console. It would be really helpful to have a bit of a comparison to allow users (including myself!) to determine which one to go for.

- [tabled](https://github.com/zhiburt/tabled)
- [prettytable-rs](https://github.com/phsym/prettytable-rs) (possibly unmaintained)
- [cli-table](https://github.com/devashishdxt/cli-table)
- [term-table-rs](https://github.com/RyanBluth/term-table-rs)
- [comfy-table](https://github.com/nukesor/comfy-table)
- etc...

**Comment by Nukesor** [comment]
Sibling ticket:
https://github.com/Nukesor/comfy-table/issues/76

Feel free to chime in!

**Comment by RyanBluth** [comment]
`term-table-rs` is pretty basic in terms of features. My goal with the project is to provide a good set of tools for rendering CLI tables, while also allowing users to bring their own tools for things like colours. One thing that is unique to `term-table-rs`(as far as I'm aware) is the ability to have different number of columns in each row of the table.
